### ISSUE TITLE
[QUESTION] Support for v12+

### ISSUE THREAD

**Issue by madmath03** [DOKOS-IO/mautic#3]
Hello,

As Frappe / ERPNext 13 is soon coming out, are there any plans for this app to support v12+ ?

**Comment by chdecultot** [comment]
Hi Mathieu,

My apologies for this very late answer. I hadn't seen the issue.
No I currently don't plan to update this app to support newer versions of Frappe/ERPNext.

Please feel free to fork it.

Have a nice day!
